main/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


app_name = 'main'

urlpatterns = [
    path('',views.landing,name='landing-page'),
    path('login/',auth_views.LoginView.as_view(template_name='main/login.html'),name='login-view'),
    path('logout/',auth_views.LogoutView.as_view(template_name='main/landing.html'),name='logout-view'),
    path('user/<str:username>',views.analytics_by_account,name='analytics-by-account'),
    path('topic/',views.analytics_by_topic,name='analytics-by-topic'),
    path('sentiment/<str:topic>',views.sentimentfilter,name='sentiment'),
    path('hashtag/',views.gethastag ,name='get-hashtags'),
    path('compare/',views.compete,name='user-comp'),
    path('register/',views.register,name='register-view'),
    path('profile/',views.profile,name='profile'),
    path('analysis/<str:userID>',views.analyze_profile,name='analyze-profile')
]

project_b2/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractBaseUser

# Create your models here.
class UserB2(models.Model):
    name = models.CharField(max_length=200,blank=True)
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True,
    )
    history = models.JSONField(default=set)
    
class User(AbstractBaseUser):
    tid=models.CharField(max_length=200,blank=True) 

main/forms.py
from django import forms
from django.contrib.auth import login,authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model=User
        fields=['username','email','password1','password2']

main/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
import matplotlib.pyplot as plt
import io
import urllib, base64
from . import quantinsta
from . import twitter_functions
from .models import *
from .forms import RegisterForm
from django.template.loader import render_to_string, get_template
from . import hashtag 
from io import BytesIO
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa 


# Create your views here.

def login(request):
    print("login func   ")
    if request.user.is_authenticated:
        print("user auth")
        '''if request.method=='POST':
            uid=request.POST.get('uid')
            # print(user_history)
            return redirect('topic/'+uid)
        
        #br = render_to_string('main/file.html')'''
        return render(request,'main/index.html')
    else:
        return redirect('main:login-view')

def register(response):
    if response.method=='POST':
        form=RegisterForm(response.POST)
        if form.is_valid():
            form.save()
            return redirect('main:landing-page')
    else:
        form=RegisterForm()
    return render(response, "main/register1.html", {'form':form})



def analytics_by_account(request,username):
    modes = {'likesperpost':{'name':'Likes per post'},'viewsvslikes':{'name':'Views vs Likes'},'compfollowers':{'name':'Followers comparison'}}
    return render(request,'main/options.html',{'profile':profile,'username':username,'modes':modes})

def analytics_by_topic(request):
    if request.user.is_authenticated:
        if request.method=="POST":
            s=str(request.POST.get('topic'))
            s=s.strip()
            if (s==''):
                return render(request, "main/sentiment.html", {'msg':'Invalid Input!'}) 
            return redirect('/sentiment/{}'.format(s))
        return render(request, "main/sentiment.html")
    return render(request, "main/landing.html", {'msg':'Please login to use this module!'})

def sentimentfilter(request, topic):
    try:
        if request.method=="POST":
            twitter_functions.twitter_credentials()
            df,positive,negative,neutral = twitter_functions.twitter_query(topic)
            df=df.iloc[:,:]
            twitter_functions.sentplot(df)
            s=str(request.POST.get('Sentiment'))
            msg= ''
            if(s!='All' and s!='None'):
                df = df[df['sentiment'] == s]
                msg= ' [Showing data of only {} sentiment]'.format(s)

            rows=list(df.itertuples(index=False))
            text= ''
            for i in df['text']:
                text+='. '+ str(i)
        
            summary = twitter_functions.summarize(text, 5)

            sent = render_to_string('main/sent.html')

            #wordcloud
            fig = twitter_functions.wordcloud(twitter_functions.tweetClean(df))

            rows=list(df.itertuples(index=False))
            
            buf1 = io.BytesIO()
            fig.savefig(buf1,format='png')
            buf1.seek(0)
            string1 = base64.b64encode(buf1.read())
            uri1 =  urllib.parse.quote(string1)

            return render(request,'main/analysis.html',{'sent':sent, 'wordcloud': uri1,'data':rows,'topic':topic+msg,'pos':positive,'neg':negative,'neu':neutral, 'summary':summary})
        twitter_functions.twitter_credentials()
        df,positive,negative,neutral = twitter_functions.twitter_query(topic)
        df=df.iloc[:,:]
        twitter_functions.sentplot(df)

        rows=list(df.itertuples(index=False))
        sent = render_to_string('main/sent.html')
        #wordcloud
        fig = twitter_functions.wordcloud(twitter_functions.tweetClean(df))

        rows=list(df.itertuples(index=False))
        text= ''
        for i in df['text']:
            text+='. '+ str(i)
        
        summary = twitter_functions.summarize(text, 5)
        buf1 = io.BytesIO()
        fig.savefig(buf1,format='png')
        buf1.seek(0)
        string1 = base64.b64encode(buf1.read())
        uri1 =  urllib.parse.quote(string1)

        return render(request,'main/analysis.html',{'summary':summary,'sent':sent, 'wordcloud': uri1,'data':rows,'topic':topic,'pos':positive,'neg':negative,'neu':neutral})
    except:
        return render(request, "main/sentiment.html", {'msg':'Invalid Input!'}) 
def compete(request):
    if request.method=='POST':
        uid=request.POST.get('uid')
        tweet,fol,like,infc=twitter_functions.score_compare(uid.split(","))
        inf = render_to_string('main/inf.html')
        reach = render_to_string('main/reach.html')
        pop = render_to_string('main/pop.html')
        likes = render_to_string('main/likes.html')
        followers = render_to_string('main/followers.html')
        return render(request, "main/user_comp.html", {'uid':uid, 'pop': pop, 'reach': reach, 'inf':inf, 'likes':likes, 'followers':followers,
                                                       'tname':tweet['screenname'].to_string()[1:], 'tcount':tweet['tweet_count'].to_string()[1:], 
                                                       'fname':fol['screenname'].to_string()[1:], 'fcount':fol['no_of_followers'].to_string()[1:], 
                                                       'lname':like['screenname'].to_string()[1:], 'lcount':like['no_of_likes'].to_string()[1:], 
                                                       'iname':infc['screenname'].to_string()[1:], 'icount':infc['inf'].to_string()[1:]} )
    return render(request, "main/user_input.html")

def gethastag(request):
    if request.method=='POST':
        content=request.POST.get('content')
        hashtags= hashtag.gethash(content)
        #print(hashtags)
        
        return render(request, "main/showhash.html", {'hashtags': " ".join(hashtags), 'content':content} )
    data= twitter_functions.get_trends_india()
    data = list(data.itertuples(index=False))
    return render(request, "main/gethashtags.html",{'data':data})

def html_to_pdf(template_src, context_dict={}):
     template = get_template(template_src)
     html  = template.render(context_dict)
     result = BytesIO()
     pdf = pisa.pisaDocument(BytesIO(html.encode("ISO-8859-1")), result)
     if not pdf.err:
         return HttpResponse(result.getvalue(), content_type='application/pdf')
     return None
 
def profile(request):
    if request.method=='POST':
        if request.user.is_authenticated:
            tid=request.POST.get('tid')
            request.user.first_name =tid
            request.user.save()
            return render(request, "main/profile.html", {'msg':'Profile Updated Successfully!','uid':request.user.first_name})
        return render(request, "main/profile.html", {'uid':request.user.first_name})
    return render(request, "main/profile.html", {'uid':request.user.first_name})


def landing(request):
    if request.user.is_authenticated:
        print("user auth")
        return render(request, "main/index.html")
    return render(request, "main/landing.html")


def analyze_profile(request, userID):
    df,df1, no_ofFollowers, no_ofLikes,no_ofFollowing, no_ofTweetsCount=twitter_functions.get_userdata(userID)
    twitter_functions.get_graphs(df,df1)
    favcount = render_to_string('main/favcount.html')
    rtcount = render_to_string('main/rtcount.html')
    eng = render_to_string('main/eng.html')
    sentcount = render_to_string('main/sentcount.html')
    
    
    
    return render(request, "main/profile_analysis.html", {'uid':userID, 'favcount': favcount, 'rtcount': rtcount, 'eng':eng, 'sentcount':sentcount,
                                                    'tcount':no_ofTweetsCount, 
                                                    'fcount':no_ofFollowers, 
                                                    'lcount':no_ofLikes})

main/templates/includes/footer-fullscreen.html
    <footer class="py-5">
      <div class="container">
        <!--div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="copyright text-center text-xl-left text-muted">
                <a target="_blank" 
                   href="https://appseed.us/admin-dashboards/django" 
                   class="font-weight-bold ml-1" target="_blank">More Dashboards</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
               &copy; <a target="_blank" 
                         href="https://bit.ly/3fKQZaL">Creative-Tim</a> 
               - coded by <a target="_blank" href="https://appseed.us">AppSeed</a>
            </div>
          </div>
        </div-->
      </div>
    </footer>

main/templates/includes/footer.html
      <!-- Footer -->
      <footer class="footer">
        <div class="row align-items-center justify-content-xl-between">
          <div class="col-xl-6">
            <div class="text-center text-xl-left text-muted">
              <a href="https://github.com/rutvikdumre/twitter-sentiment" 
                 class="font-weight-bold ml-1" target="_blank">Project B2 (Beta)</a>
            </div>
          </div>
          <div class="col-xl-6">
            <div class="text-center text-xl-right text-muted">
              <a href="/" 
                 class="font-weight-bold ml-1" target="_blank"> Project B2</a> 
                 a project by students of <a target="_blank" href="https://www.nmims.edu/">NMIMS University</a>
            </div>
          </div>
        </div>
      </footer>

main/templates/includes/navigation-fullscreen.html
<nav id="navbar-main" class="navbar navbar-horizontal navbar-transparent navbar-main navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand" href="/">
      <!--img src="/static/assets/img/brand/white.png" alt="Argon Design - Template Starter Logo."-->project b2
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="navbar-collapse navbar-custom-collapse collapse" id="navbar-collapse">
      <div class="navbar-collapse-header">
        <div class="row">
          <div class="col-6 collapse-brand">
            <a href="/">
              <img src="/static/assets/img/brand/blue.png">
            </a>
          </div>
          <div class="col-6 collapse-close">
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbar-collapse" aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
              <span></span>
              <span></span>
            </button>
          </div>
        </div>
      </div>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a href="{% url 'main:login-view' %}" class="nav-link">
            <span class="nav-link-inner--text">Login</span>
          </a>
        </li>
        <li class="nav-item">
          <a href="{% url 'main:register-view' %}" class="nav-link">
            <span class="nav-link-inner--text">Register</span>
          </a>
        </li>
      </ul>
      <hr class="d-lg-none" />
      
    </div>
  </div>
</nav>

main/templates/includes/navigation.html
<nav class="navbar navbar-top navbar-expand navbar-dark bg-primary border-bottom">
  <div class="container-fluid">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Search form -->
      
      <!-- Navbar links -->
      <ul class="navbar-nav align-items-center  ml-md-auto ">
        <li class="nav-item d-xl-none">
          <!-- Sidenav toggler -->
          <div class="pr-3 sidenav-toggler sidenav-toggler-dark" data-action="sidenav-pin" data-target="#sidenav-main">
            <div class="sidenav-toggler-inner">
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
              <i class="sidenav-toggler-line"></i>
            </div>
          </div>
        </li>
        <li class="nav-item d-sm-none">
          <a class="nav-link" href="#" data-action="search-show" data-target="#navbar-search-main">
            <i class="ni ni-zoom-split-in"></i>
          </a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-bell-55"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-xl  dropdown-menu-right  py-0 overflow-hidden">
            <!-- Dropdown header -->
            <div class="px-3 py-3">
              <h6 class="text-sm text-muted m-0">You have <strong class="text-primary">1</strong> notification.</h6>
            </div>
            <!-- List group -->
            <div class="list-group list-group-flush">
              <a href="#!" class="list-group-item list-group-item-action">
                <div class="row align-items-center">
                  <div class="col-auto">
                    <!-- Avatar -->
                    <img alt="Image placeholder" src="/static/assets/img/theme/team-1.jpg" class="avatar rounded-circle">
                  </div>
                  <div class="col ml--2">
                    <div class="d-flex justify-content-between align-items-center">
                      <div>
                        <h4 class="mb-0 text-sm">Project B2</h4>
                      </div>
                      <div class="text-right text-muted">
                        <small>Admin</small>
                      </div>
                    </div>
                    <p class="text-sm mb-0">Hi user, welcome to projectB2! We hope to meet you analytical requirements.</p>
                  </div>
                </div>
              </a>
              
            </div>
            <!-- View all -->
            <a href="#!" class="dropdown-item text-center text-primary font-weight-bold py-3">View all</a>
          </div>
        </li>
        <li class="nav-item dropdown" style="display: none;">
          <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="ni ni-ungroup"></i>
          </a>
          <div class="dropdown-menu dropdown-menu-lg dropdown-menu-dark bg-default  dropdown-menu-right ">
            <div class="row shortcuts px-4">
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-red">
                  <i class="ni ni-calendar-grid-58"></i>
                </span>
                <small>Calendar</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-orange">
                  <i class="ni ni-email-83"></i>
                </span>
                <small>Email</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-info">
                  <i class="ni ni-credit-card"></i>
                </span>
                <small>Payments</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-green">
                  <i class="ni ni-books"></i>
                </span>
                <small>Reports</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-purple">
                  <i class="ni ni-pin-3"></i>
                </span>
                <small>Maps</small>
              </a>
              <a href="#!" class="col-4 shortcut-item">
                <span class="shortcut-media avatar rounded-circle bg-gradient-yellow">
                  <i class="ni ni-basket"></i>
                </span>
                <small>Shop</small>
              </a>
            </div>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav align-items-center  ml-auto ml-md-0 ">
        <li class="nav-item dropdown">
          <a class="nav-link pr-0" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <div class="media align-items-center">
              <span class="avatar avatar-sm rounded-circle">
                <img alt="Image placeholder" src="/static/assets/img/theme/team-4.jpg">
              </span>
              <div class="media-body  ml-2  d-none d-lg-block">
                <span class="mb-0 text-sm  font-weight-bold">
                  {{ request.user.username }}
                </span>
              </div>
            </div>
          </a>
          <div class="dropdown-menu  dropdown-menu-right ">
            <div class="dropdown-header noti-title">
              <h6 class="text-overflow m-0">Welcome!</h6>
            </div>
            <a href="{% url 'main:profile' %}" class="dropdown-item">
              <i class="ni ni-single-02"></i>
              <span>My profile</span>
            </a>
            <a target="_blank" href="http://appseed.us/support" class="dropdown-item">
              <i class="ni ni-support-16"></i>
              <span>Support</span>
            </a>
            <div class="dropdown-divider"></div>
            <a href="{% url 'main:logout-view' %}" class="dropdown-item">
              <i class="ni ni-user-run text-red"></i>
              <span>Logout</span>
            </a>
          </div>
        </li>
      </ul>
    </div>
  </div>
</nav>

main/templates/includes/scripts.html
  <script src="/static/assets/vendor/jquery/dist/jquery.min.js"></script>
  <script src="/static/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/js-cookie/js.cookie.js"></script>
  <script src="/static/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js"></script>
  <script src="/static/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js"></script>

main/templates/includes/sidenav.html
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
  <div class="scrollbar-inner">
    <!-- Brand -->
    <div class="sidenav-header  align-items-center">
      <a class="navbar-brand" href="/">
        <img src="/static/assets/img/brand/blue.png" class="navbar-brand-img" alt="Argon Design - Jinja Template Logo.">
      </a>
    </div>
    <div class="navbar-inner">
      <!-- Collapse -->
      <div class="collapse navbar-collapse" id="sidenav-collapse-main">
        <!-- Nav items -->
        <div class="navbar-collapse-header">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a href="/">
                <img src="/static/assets/img/brand/blue.png">
              </a>
            </div>
            <div class="col-6 collapse-close">
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            </div>
          </div>
        </div>
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if 'index' in segment %} active {% endif %}" href="/">
              <i class="ni ni-tv-2 text-primary"></i>
              <span class="nav-link-text">Home</span>
            </a>
          </li>
        </ul>
        <hr class="my-3">
        <!-- Heading -->
        <h6 class="navbar-heading p-0 text-muted">
          <span class="docs-normal">Tools</span>
        </h6>
        
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link {% if 'profile' in segment %} active {% endif %}" href="{% url 'main:user-comp' %}">
              <i class="ni ni-single-02 text-yellow"></i>
              <span class="nav-link-text">User Compare</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if 'tables' in segment %} active {% endif %}" href="{% url 'main:analytics-by-topic' %}">
              <i class="ni ni-bullet-list-67 text-default"></i>
              <span class="nav-link-text">Sentiment</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link {% if 'tables' in segment %} active {% endif %}" href="{% url 'main:get-hashtags' %}">
              <i class="ni ni-bullet-list-67 text-default"></i>
              <span class="nav-link-text">Hashtag Recommendations</span>
            </a>
          </li></ul>
          <hr class="my-3">
          <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'main:logout-view' %}">
              <i class="ni ni-user-run text-red"></i>
              <span class="nav-link-text">Logout</span>
            </a>
          </li>            
        </ul>
        <!-- Divider -->
        
        
        
      </div>
    </div>
  </div>
</nav>